### ISSUE TITLE
Laravel version 6.18.8

### ISSUE THREAD

**Issue by scottsuhy** [Chatter-Laravel/core#15]
What am I missing?  It's installed, i'm logged in, but there is nothing at /forums. 
I installed core ^6  on top of a fresh install of 6.18.8 (tried getting Laravel 7 to work but it would not resolve dependencies). ...but I have no /forums.

my web.php file is this--which is quite different than the devdojo routes:

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

**Comment by tpjigar** [comment]
Same issue nothing in /forums link.
in database testing data already available ...

**Comment by tpjigar** [comment]
Issue because of latest version of "sass-loader". downgrade "sass-loader" version and it will be working like charm.. 

follow this command. 

**

> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0

**

**Comment by scottsuhy** [comment]
It didn't seem to have an impact.  I even reinstalled laravel.  Here is process:

composer create-project laravel/laravel chatter 6.18.0
composer require "chatter-laravel/core"

bad (see readme, removed dupe slashes): php artisan vendor:publish --provider "Chatter\\Core\\ChatterServiceProvider" 
fix: php artisan vendor:publish --provider "Chatter\Core\ChatterServiceProvider"

composer dump-autoload
add: update .env file with database creds
php artisan chatter:install (chose option to add data to database)
updated app.php and kernal.php (as in step 4 and 5 on https://github.com/Chatter-Laravel/core)
npm install tailwindcss
npm uninstall --save-dev sass-loader
npm install --save-dev sass-loader@7.1.0
php artisan serve --port=7777
http://127.0.0.1:7777/forums

see [https://imgur.com/yKcF5TI](https://imgur.com/yKcF5TI) for picture

**Comment by sbarbat** [comment]
@scottsuhy do you mind posting here you packages.json and composer.json files?

**Comment by scottsuhy** [comment]
**package.json:**
`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "cross-env": "^7.0",
        "emoji-mart-vue": "^2.6.6",
        "gsap": "^3.0.1",
        "laravel-mix": "^4.0.14",
        "laravel-mix-purgecss": "^4.1",
        "laravel-mix-tailwind": "^0.1.0",
        "lodash": "^4.17.13",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "tailwindcss": "^1.2.0",
        "tiptap": "^1.26.4",
        "tiptap-extensions": "^1.28.4",
        "vue": "^2.6.10",
        "vue-content-loader": "^0.2.2",
        "vue-router": "^3.1.3",
        "vue-template-compiler": "^2.6.10",
        "vueditor": "^0.3.1",
        "vuex": "^3.1.2"
    }
}
`
**composer.json**
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "chatter-laravel/core": "^6.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by scottsuhy** [comment]
[chatter.zip](https://github.com/Chatter-Laravel/core/files/4497439/chatter.zip)

**Comment by sbarbat** [comment]
I tried to run it with your same versions and it seems to work fine. Did you followed all the instructions? Make sure you have the traits `use HasApiTokens, Notifiable, CanDiscuss;` included in your User model.

**Comment by sdunayer** [comment]
The problem occurs because chatter:install fails while running the "npm run dev" command.  Rolling back sass-loader does appear to solve the issue.  In this case, he did the downgrade after the chatter:install and then failed to do an "npm run dev" to create the necessary assets.  If you run the "npm run dev" everything will then work properly.

**Comment by sbarbat** [comment]
This is an incompatibility between [Laravel Mix and sass-loader 8](https://github.com/JeffreyWay/laravel-mix/issues/2206)

Try:
```bash
npm uninstall --save-dev sass-loader
npm install --save-dev sass-loader@^7
npm run prod
```
