### ISSUE TITLE
Issue with user avatar

### ISSUE THREAD

**Issue by nova73-alt** [Chatter-Laravel/core#19]
How do i add avatar , I already have avatar but it keep on generating other girl avatar, i already configured configure.php without success

**Comment by sbarbat** [comment]
Hey @nova73-alt, check the file [CanDiscuss.php](https://github.com/Chatter-Laravel/core/blob/a32da66d9729a5f6baa4006adff37bf2d09a97da/src/Traits/CanDiscuss.php#L75). You need to override the `getForumAvatarAttribute()` on your User model:

```php
    /**
     * Returns the url of the avatar for each forum user
     *
     * @return string
     */
    public function getForumAvatarAttribute(): string
    {
        return 'RETURN HERE YOUR USER PROFILE PIC';
    }
```
