### ISSUE TITLE
Issues with buttons

### ISSUE THREAD

**Issue by allthepews** [Chatter-Laravel/core#3]
I was able to get it up and running, so I thought. 

New Discussion, Edit, Delete, Post buttons do nothing but there are no errors on console.

Any idea what can be the cause?

**Comment by sbarbat** [comment]
@allthepews I haven't make any changes for lastest versions of Laravel, for sure someone make the changes on the original repository and still as a PR, we'll need to check pending PR's on the other repository and copy the changes.

What version of Laravel you're using?

**Comment by beepy** [comment]
This video https://www.youtube.com/watch?v=Zk-2nKIMntI states that this fork https://github.com/webdevmatics/chatter works with Laravel 6

**Comment by allthepews** [comment]
> @allthepews I haven't make any changes for lastest versions of Laravel, for sure someone make the changes on the original repository and still as a PR, we'll need to check pending PR's on the other repository and copy the changes.
> 
> What version of Laravel you're using?

5.8

**Comment by allthepews** [comment]
> This video https://www.youtube.com/watch?v=Zk-2nKIMntI states that this fork https://github.com/webdevmatics/chatter works with Laravel 6

Tried running this no errors on install but once I try to open /forums I get 'Trying to get property 'markdown' of non-object'

**Comment by sbarbat** [comment]
Bear with me a litte bit. I'm working on a whole refactoring of the blog to single page app with Vue that will be commiting on the next couple of days.

**Comment by sbarbat** [comment]
@allthepews @beepy would you like to try the new implementation? 😃

**Comment by allthepews** [comment]
> @allthepews @beepy would you like to try the new implementation? 😃

Tried the new implementation had a model error due to my package, fixed that but that forum content is empty. Verified by direct link of discussions and information is stored on DB. However, it does not show up on the /forums/

**Comment by sbarbat** [comment]
@allthepews can you share your logs or a bit more information? Thanks.

**Comment by allthepews** [comment]
@sbarbat logs are not showing any errors. forums/ homepage has no content except for header and footer.  @yield('content') @section('info') should be returning the datasets.

**Comment by sbarbat** [comment]
Did you run the `php artisan preset chatter` command? Are you testing in an existing project?

**Comment by allthepews** [comment]
@sbarbat Trying on an existing project. My first attempt with the preset command is it removed my current project. I went ahead and manually ran the auto-load, migrations, etc.

**Comment by sbarbat** [comment]
Seems to be a problem with the Vue files. Are you including `require('./chatter/app')` in your app.js file? If you try to access `/api/chatter/discussion` does it return the JSON with the discussions? Since is an existing project you will need to include Tailwind CSS as well

**Comment by allthepews** [comment]
@sbarbat Just tried running the preset command, replaces my current project and still doesn't show any forum content on /forums or /public. api/chatter is not returning any JSON data.

**Comment by sbarbat** [comment]
Can you post the return of the API call? If it shows and error, that must be logged on the logs

**Comment by allthepews** [comment]
@sbarbat `[2019-12-12 18:00:48] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'chatter_post.discussion_id' in 'where clause' (SQL: select count(*) as aggregate from `chatter_post` where `chatter_post`.`discussion_id` = 3 and `chatter_post`.`discussion_id` is not null and `chatter_post`.`deleted_at` is null) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'chatter_post.discussion_id' in 'where clause' (SQL: select count(*) as aggregate from `chatter_post` where `chatter_post`.`discussion_id` = 3 and `chatter_post`.`discussion_id` is not null and `chatter_post`.`deleted_at` is null) at /data/www/default/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'chatter_post.discussion_id' in 'where clause' at /data/www/default/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'chatter_post.discussion_id' in 'where clause' at /data/www/default/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)`

**Comment by allthepews** [comment]
@sbarbat I modified the tables according to your changes of removing the chatter_ prefix.
API returns in JSON the data however still blank on the webpage end.

**Comment by sbarbat** [comment]
I just made a few fixes on Vue, can you try to update the package with `composer update chatter-laravel-core` and compile with `npm run dev`? Let me know what happened

**Comment by allthepews** [comment]
@sbarbat `npm run dev` resulted in errors found below..

> 1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@4.2.0
3 info using node@v13.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/data/www/default/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle @~dev: CWD: /data/www/default
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 2  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at EventEmitter.emit (events.js:219:5)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:219:5)
14 verbose stack     at maybeClose (internal/child_process.js:1027:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:5)
15 verbose pkgid @
16 verbose cwd /data/www/default
17 error Linux 4.4.0-142-generic
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "run" "dev"
19 error node v13.3.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error @ dev: `npm run development`
23 error Exit status 2
24 error Failed at the @ dev script 'npm run development'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run development
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

>

**Comment by sbarbat** [comment]
@allthepews any luck with that?
