### ISSUE TITLE
Installation failed on laravel 8 

### ISSUE THREAD

**Issue by haifizan5573** [Chatter-Laravel/core#30]
Problem 1
    - Installation request for chatter-laravel/core dev-master -> satisfiable by chatter-laravel/core[dev-master].
    - Conclusion: remove laravel/framework v8.18.1
    - Conclusion: don't install laravel/framework v8.18.1
    - chatter-laravel/core dev-master requires laravel/framework ^5.8 || ^6 || ^7 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev, 7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v8.18.1].
    - Can only install one of: laravel/framework[5.8.x-dev, v8.18.1].
    - Can only install one of: laravel/framework[6.x-dev, v8.18.1].
    - Installation request for laravel/framework (locked at v8.18.1, required as ^8.0) -> satisfiable by laravel/framework[v8.18.1].

Do you guys have any ideas to fixed this. Thanks

**Comment by jeremiahsherrill** [comment]
Will this be updated to support Laravel 8?  Or 9?   Or is this a dead package?

**Comment by sbarbat** [comment]
Just merged an update on master to make it work with Laravel 8 🎉
