### ISSUE TITLE
After installing - SQL Error why?

### ISSUE THREAD

**Issue by wege2003** [Chatter-Laravel/core#48]
Hey tehre,
can you help me with this issue please
![image](https://user-images.githubusercontent.com/31622452/144409960-242fbc3d-ce6a-407b-a52d-e2c32f3fcab0.png)

**Comment by sbarbat** [comment]
You probably need to install the `php-mysql` driver, take a look at this [Stackoverflow answer](https://stackoverflow.com/questions/35240414/laravel-5-pdoexception-could-not-find-driver)
