### ISSUE TITLE
/forums is empty

### ISSUE THREAD

**Issue by cherif-bayo** [Chatter-Laravel/core#7]
i followed the readme
i installed the package on fresh laraval 6 app to test before installing on my app. 
But i get a blank page when i navigate throught http://localhost:8000/forums.

**Comment by sbarbat** [comment]
Hi @cherif-bayo. Could you send some more information about the error? Output of the browser console, Laravel logs so we can debug? Thanks 🙏

**Comment by cherif-bayo** [comment]
Hello @sbarbat , My browser console error 
`app.js:38105 [Vue warn]: Unknown custom element: <app> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)
warn @ app.js:38105
`
And my Laravel Log:

local.ERROR: Use of undefined constant css - assumed 'css' (this will throw an Error in a future version of PHP) (View: /mnt/c/Users/cbayo/Desktop/Folders/chatter-newss/resources/views/layouts/app.blade.php) {"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Use of undefined constant css - assumed 'css' (this will throw an Error in a future version of PHP) (View: /mnt/c/Users/cbayo/Desktop/Folders/chatter-newss/resources/views/layouts/app.blade.php) at /mnt/c/Users/cbayo/Desktop/Folders/chatter-newss/resources/views/layouts/app.blade.php:21)

**Comment by sbarbat** [comment]
That doesn't seem to be an issue, is just a Vue Warning. Do you have any information on your database? Maybe you can try to run the seeds to preload some testing information and see if it works. Just run `php artisan db:seed --class ChatterTableSeeder`
