### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by irvine48** [Chatter-Laravel/core#8]
npm ERR! code EPROTO
npm ERR! syscall symlink
npm ERR! path ../semver/bin/semver.js
npm ERR! dest /home/vagrant/Code/chatter/node_modules/@babel/compat-data/node_modules/.bin/semver
npm ERR! errno -71
npm ERR! EPROTO: protocol error, symlink '../semver/bin/semver.js' -> '/home/vagrant/Code/chatter/node_modules/@babel/compat-data/node_modules/.bin/semver'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-01-12T06_54_24_709Z-debug.log

Anyone facing this issue? test install in vagrant, not pass through the install steps.

**Comment by sbarbat** [comment]
@irvine48 can you advise the version of Laravel and of the package you are using? Thanks.

**Comment by irvine48** [comment]
Laravel 6.10.1
npm 6.11.2

**Comment by sbarbat** [comment]
Hey, any update on this?
